---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define socket file
  set_fact:
    mysql_cfg_socket: "{{ __mysql_cfg_socket }}"
  when: mysql_cfg_socket is not defined

- name: Define error log
  set_fact:
    mysql_cfg_log_error: "{{ __mysql_cfg_log_error }}"
  when: mysql_cfg_log_error is not defined

- name: Define slow log
  set_fact:
    mysql_cfg_slow_query_log_file: "{{ __mysql_cfg_slow_query_log_file }}"
  when: mysql_cfg_slow_query_log_file is not defined

- name: Define configuration file
  set_fact:
    mysql_cfg_cnffile: "{{ __mysql_cfg_cnffile }}"
  when: mysql_cfg_cnffile is not defined

- name: Define configuration directories
  set_fact:
    mysql_cfg_cnfdir: "{{ __mysql_cfg_cnfdir }}"
  when: mysql_cfg_cnfdir is not defined

- include: "setup-{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
